NAME     = typing-game
PROJ_DIR = $(AM_HOME)/../am-kernels/kernels/typing-game

# Change $(NAME) and $(PROJ_DIR) at your convenience

# BIN_FILE = $(PROJ_DIR)/build/$(NAME)-$(AM_ARCHS).bin
#
#   Note:
#   this is the default $(BIN_FILE). If your project follows this convention, just comment this.
#   Otherwise, modify this line at your convenience.


# define operation_sequence =
# 	@$(MAKE) -s -C $(PROJ_DIR) ARCH=$(AM_ARCHS) image > /dev/null
# endef
#
#   Note: 
#   this is the default $(operation_sequence). If your project follows this convention, just comment this.
#   Otherwise, modify this line at your convenience.

ROOT_DIR = $(abspath ../..)
include $(ROOT_DIR)/scripts/refer.mk
